name: Manifest-Generator

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled

jobs:
  Manifest-Generator:
    uses: amalx-ssrc/tii_sel4_build_test/.github/workflows/pr.yml@tii/dev-manifest
    with: 
      branch: ${{ github.head_ref }}
    secrets:
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      CI_SSH_KEY: ${{ secrets.CI_SSH_KEY}}