name: Manifest-Generator

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  Manifest-Generator:
    uses: amalx-ssrc/tii_sel4_build_test/.github/workflows/prepare-manifest.yml@tii/development-test
    with: 
      branch: ${{ github.head_ref }}
    secrets:
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}